<a href="https://colab.research.google.com/github/CIT-NLP/NLP-final-project/blob/main/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!gdown https://drive.google.com/uc?id=1sruWwskaVr76vsy8T99SyesWHIncqKzT

Downloading...
From: https://drive.google.com/uc?id=1sruWwskaVr76vsy8T99SyesWHIncqKzT
To: /content/processed_dataframe.csv
100% 223M/223M [00:01<00:00, 167MB/s]


In [2]:
import pandas as pd

df = pd.read_csv("./processed_dataframe.csv")

df

wikipedia id                                         movie name  \
0            975900                                     Ghosts of Mars   
1           6631279                                        Little city   
2          11250635                            The Mechanical Monsters   
3             77856                                       Mary Poppins   
4            156558                                           Baby Boy   
...             ...                                                ...   
16604      19286279                                        Kalai Arasi   
16605        664006                                      Guilty as Sin   
16606      15394941                                        Gopi Kishan   
16607      23851782                                    The Ghost Train   
16608        913762  The Super Dimension Fortress Macross II: Lover...   

                                                  genres  \
0      ['action', 'adventure', 'thriller', 'horror', ...   
1                         ['drama', 'comedy', 'romance']   
2      ['action', 'adventure', 'family', 'short film'...   
3               ['drama', 'comedy', 'family', 'fantasy']   
4                                     ['drama', 'crime']   
...                                                  ...   
16604  ['drama', 'action', 'romance', 'science fiction']   
16605                              ['crime', 'thriller']   
16606             ['drama', 'comedy', 'action', 'crime']   
16607                    ['comedy', 'crime', 'thriller']   
16608  ['drama', 'adventure', 'short film', 'science ...   

                                                 summary  \
0      Set in the second half of the 22nd century, th...   
1      Adam, a San Francisco-based artist who works a...   
2       The story starts as one of the robots flies i...   
3      The film opens with Mary Poppins  perched in a...   
4      A young 20-year-old named Jody  lives with his...   
...                                                  ...   
16604  Kalai Arasi' is a well-blended story of romanc...   
16605  Jennifer Haines  is an up-and-coming Chicago a...   
16606  Kishan  killed a man in his childhood when the...   
16607  {{plot}} The film opens with a Great Western e...   
16608  The story takes place in the year 2092,The Sup...   

                                                unigrams  \
0      ['set', 'second', 'half', '22nd', 'century', '...   
1      ['adam', 'san', 'francisco', 'based', 'artist'...   
2      ['story', 'starts', 'robots', 'flies', 'scient...   
3      ['film', 'opens', 'mary', 'poppins', 'perched'...   
4      ['young', '20', 'year', 'old', 'named', 'jody'...   
...                                                  ...   
16604  ['kalai', 'arasi', 'blended', 'story', 'romanc...   
16605  ['jennifer', 'haines', 'coming', 'chicago', 'a...   
16606  ['kishan', 'killed', 'man', 'childhood', 'man'...   
16607  ['plot', 'film', 'opens', 'great', 'western', ...   
16608  ['story', 'takes', 'place', 'year', '2092,the'...   

                                              lemmatized  \
0      ['set', 'second', 'half', '22nd', 'century', '...   
1      ['adam', 'san', 'francisco', 'base', 'artist',...   
2      ['story', 'start', 'robot', 'fly', 'scientist'...   
3      ['film', 'open', 'mary', 'poppins', 'perch', '...   
4      ['young', '20', 'year', 'old', 'name', 'jody',...   
...                                                  ...   
16604  ['kalai', 'arasi', 'blend', 'story', 'romance'...   
16605  ['jennifer', 'haines', 'come', 'chicago', 'att...   
16606  ['kishan', 'kill', 'man', 'childhood', 'man', ...   
16607  ['plot', 'film', 'open', 'great', 'western', '...   
16608  ['story', 'take', 'place', 'year', '2092,the',...   

                                               sentences  \
0      ['Set in the second half of the 22nd century, ...   
1      ['Adam, a San Francisco-based artist who works...   
2      [" The story starts as one of the robots flies.

In [ ]:
df_trunc = df[:50]

df_trunc

wikipedia id                                  movie name  \
0         975900                              Ghosts of Mars   
1        6631279                                 Little city   
2       11250635                     The Mechanical Monsters   
3          77856                                Mary Poppins   
4         156558                                    Baby Boy   
5       11448183                            Bindiya Chamkegi   
6       29528534                               Anokha Rishta   
7         261237                      The Gods Must Be Crazy   
8       12008535                                Rudo y Cursi   
9        4951456                 Kinjite: Forbidden Subjects   
10       5708633                     The Great New Wonderful   
11      12053509                                    Loverboy   
12       2647998                           The Human Tornado   
13       5894429                            Closing the Ring   
14      27556929                               Deadly Voyage   
15       4300418               The Hero: Love Story of a Spy   
16      10419077                         Raampur Ka Lakshman   
17        164387                      ...And Justice for All   
18      24282217                           The Naked Kitchen   
19       1630107                         A Zed & Two Noughts   
20      11717027             Is There a Doctor in the Mouse?   
21       3550323     Things to Do in Denver When You're Dead   
22       1072373                             Minsaara Kanavu   
23       1765938                                      Convoy   
24      18902861                              14 Going on 30   
25       1305819                                    C.H.U.D.   
26      12438366                           Mehndi Waley Hath   
27       1031231                        Black Cat, White Cat   
28       6305925                        The Astronaut Farmer   
29        196176                                  Straw Dogs   
30       2509881                                  Critters 3   
31        748616  Spring, Summer, Fall, Winter... and Spring   
32      36151270                                   Agneekaal   
33        336846                                      Grease   
34      27463222                     Vanishing on 7th Street   
35      15007384                                Le Grand jeu   
36      11692389                              The Snow Queen   
37       3829646           What Have I Done To Deserve This?   
38      27874961                               The Iron Rose   
39       3033993                               Becoming Jane   
40      30405742                                 Plug & Pray   
41        103021                            Midnight Express   
42      33144131                                    Fly Away   
43       1940449                                   RoboCop 3   
44       5384210                                    Gagamboy   
45       6703617                       The Forbidden Kingdom   
46      19389755                              Asylum Seekers   
47        362719                                    Superman   
48       2870618                            Boy called Twist   
49      21271533                                     Bleeder   

                                               genres  \
0   ['action', 'adventure', 'thriller', 'horror', ...   
1                      ['drama', 'comedy', 'romance']   
2   ['action', 'adventure', 'family', 'short film'...   
3            ['drama', 'comedy', 'family', 'fantasy']   
4                                  ['drama', 'crime']   
5                                ['comedy', 'family']   
6                ['drama', 'romance', 'world cinema']   
7   ['comedy', 'action', 'adventure', 'world cinema']   
8                       ['drama', 'comedy', 'family']   
9                     ['action', 'crime', 'thriller']   
10                                ['drama', 'comedy']   
11                              ['comedy', 'romance']  

In [ ]:
def flatten_sent(sent_list):
  ret_val = []
  for sent in sent_list: 
    ret_val.append(" ".join(sent))
  return ret_val 


df_trunc["lem_sent_join"] = df_trunc.sentences.apply(flatten_sent)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report
from sklearn.datasets import make_multilabel_classification
from sklearn.svm import SVC
from sklearn.multioutput import MultiOutputClassifier

In [ ]:
x, y = make_multilabel_classification(n_samples=5000, n_features=10,
                                      n_classes=2, random_state=0)

In [ ]:
xtrain, xtest, ytrain, ytest=train_test_split(x, y, train_size=0.95, random_state=0)

In [ ]:
from ast import literal_eval

for col in ['genres', 'unigrams', 'lemmatized', 'sentences', 'lem_sent']: 
  df[col] = df[col].apply(literal_eval)

In [ ]:
df_all = df[:100]

In [ ]:
def flatten_sent(sent_list):
  ret_val = []
  for sent in sent_list: 
    ret_val.append(" ".join(sent))
  return ret_val 


df_all["lem_sent_join"] = df_all.lem_sent.apply(flatten_sent)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
import numpy as np

X = []
y = []

for _, row in df_all.iterrows(): 
  X.extend(row['lem_sent_join'])
  for sent in row['lem_sent_join']: 
    y.append(row['genres'])

In [ ]:
len(y)

2461

In [ ]:
X

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(X)

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

# Create MultiLabelBinarizer object
mlb = MultiLabelBinarizer()

# One-hot encode data
y1 = mlb.fit_transform(y)

In [ ]:
len(y1)

2461

In [ ]:
df_all.genres.iloc[0]

['action', 'adventure', 'thriller', 'horror', 'science fiction']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.25, random_state=42)
mnb = MultinomialNB()

In [ ]:
multi_target_nb = MultiOutputClassifier(mnb, n_jobs=-1)
multi_target_nb.fit(X_train, y_train)

MultiOutputClassifier(estimator=MultinomialNB(), n_jobs=-1)

In [ ]:
y_pred = multi_target_nb.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average = 'weighted') 


print(f"accuracy is {acc}")
print(f"f1 score is {f1}")

accuracy is 0.1737012987012987
f1 score is 0.5117428491894223


In [ ]:
from sklearn.metrics import jaccard_score

jacc = jaccard_score(y_test, y_pred, average='weighted')

print(f"jaccard score is {jacc}")

jaccard score is 0.40746822332440813


Full Dataframe

In [ ]:
from ast import literal_eval

for col in ['genres', 'unigrams', 'lemmatized', 'sentences', 'lem_sent']: 
  df[col] = df[col].apply(literal_eval)

In [ ]:
def flatten_sent(sent_list):
  ret_val = []
  for sent in sent_list: 
    ret_val.append(" ".join(sent))
  return ret_val 


df["lem_sent_join"] = df.lem_sent.apply(flatten_sent)

In [ ]:
import numpy as np

X = []
y = []

for _, row in df.iterrows(): 
  X.extend(row['lem_sent_join'])
  for sent in row['lem_sent_join']: 
    y.append(row['genres'])

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(X)

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

# Create MultiLabelBinarizer object
mlb = MultiLabelBinarizer()

# One-hot encode data
y1 = mlb.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.25, random_state=42)
mnb = MultinomialNB()

In [ ]:
multi_target_nb = MultiOutputClassifier(mnb, n_jobs=-1)
multi_target_nb.fit(X_train, y_train)

MultiOutputClassifier(estimator=MultinomialNB(), n_jobs=-1)

In [ ]:
y_pred = multi_target_nb.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import jaccard_score

acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average = 'weighted') 
jacc = jaccard_score(y_test, y_pred, average='weighted')


print(f"accuracy is {acc}")
print(f"f1 score is {f1}")
print(f"jaccard score is {jacc}")

accuracy is 0.1160965468572682
f1 score is 0.44883674881249025
jaccard score is 0.31301755364602


In [ ]:
from sklearn.metrics import multilabel_confusion_matrix

conf = multilabel_confusion_matrix(y_test, y_pred)

In [ ]:
from sklearn.metrics import classification_report

print(conf)
print(classification_report(y_test,y_pred))

[[[ 74802   1280]
  [ 17773  11006]]

 [[ 88520    205]
  [ 12863   3273]]

 [[ 65625   2472]
  [ 22480  14284]]

 [[ 83957    254]
  [ 17073   3577]]

 [[104183      3]
  [   674      1]]

 [[ 33276  15660]
  [  9014  46911]]

 [[ 88149    220]
  [ 13657   2835]]

 [[ 93321     76]
  [  9896   1568]]

 [[ 90463     80]
  [ 12713   1605]]

 [[ 95449     39]
  [  9081    292]]

 [[ 77551   1053]
  [ 19755   6502]]

 [[ 93193    142]
  [  9469   2057]]

 [[ 99466     30]
  [  4916    449]]

 [[102973      8]
  [  1879      1]]

 [[ 74045    979]
  [ 21248   8589]]

 [[ 83801    616]
  [ 15168   5276]]]
              precision    recall  f1-score   support

           0       0.90      0.38      0.54     28779
           1       0.94      0.20      0.33     16136
           2       0.85      0.39      0.53     36764
           3       0.93      0.17      0.29     20650
           4       0.25      0.00      0.00       675
           5       0.75      0.84      0.79     55925
           6 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Full-Summary Version

In [ ]:
type(df_all['summary'][0])

str

In [ ]:
import numpy as np

df_all = df[:100]

X_doc = []
y_doc = []

for _, row in df.iterrows(): 
  #X_doc.append(str(row['summary']))
  #for sent in row['summary']: 
  y_doc.append(row['genres'])

In [ ]:
X_doc

In [ ]:
lst = []

for _, row in df.iterrows():
  strng = " ".join(row['lemmatized'])
  #print(strng)
  lst.append(strng)

lst

In [ ]:
len(lst)

16609

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

# Create MultiLabelBinarizer object
mlb = MultiLabelBinarizer()

# One-hot encode data
y1 = mlb.fit_transform(y_doc)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(lst, y1, test_size=0.25, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()

In [ ]:
from sklearn.multioutput import MultiOutputClassifier

multi_target_nb = MultiOutputClassifier(mnb, n_jobs=-1)
multi_target_nb.fit(X_train, y_train)

MultiOutputClassifier(estimator=MultinomialNB(), n_jobs=-1)

In [ ]:
y_pred = multi_target_nb.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import jaccard_score

acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average = 'weighted') 
jacc = jaccard_score(y_test, y_pred, average='weighted')


print(f"accuracy is {acc}")
print(f"f1 score is {f1}")
print(f"jaccard score is {jacc}")

accuracy is 0.0007223693715386468
f1 score is 0.1711434876755551
jaccard score is 0.13420011070730686


In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.01      0.01      1069
           1       0.00      0.00      0.00       582
           2       0.88      0.08      0.15      1552
           3       0.00      0.00      0.00       795
           4       0.00      0.00      0.00        51
           5       0.68      0.92      0.78      2265
           6       1.00      0.00      0.01       629
           7       0.00      0.00      0.00       388
           8       0.00      0.00      0.00       480
           9       0.00      0.00      0.00       332
          10       0.67      0.00      0.00      1027
          11       0.00      0.00      0.00       359
          12       0.00      0.00      0.00       281
          13       0.00      0.00      0.00        68
          14       0.00      0.00      0.00      1081
          15       0.00      0.00      0.00       873

   micro avg       0.69      0.19      0.30     11832
   macro avg       0.26   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
